name: Scratch

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Appium Server
        shell: bash
        run: |
          set -ex
          echo "Install and Running Appium Server as a Background process"
          sudo npm install -g appium --unsafe-perm=true --allow-root
          appium -v
          appium &>/dev/null &

      - name: Run UITests Android
        run: |
          dotnet run --project src/Xappium.Cli/Xappium.Cli.csproj -c Release -- -uitest sample/TestApp.UITests/TestApp.UITests.csproj -app sample/TestApp.Android/TestApp.Android.csproj --logger normal
